### ISSUE TITLE
Centos 7 auto update doesn't install updates

### ISSUE THREAD

**Issue by jyrkij** [geerlingguy/ansible-role-security#10]
This is true at least for Centos 7, I haven't checked other RedHat based distros.

Enabling `security_autoupdate_enabled` doesn't install the updates. This is because the default configuration file that comes with `yum` and `yum-cron` (`/etc/yum/yum-cron.conf`) contains these rows:

    [commands]
    #  What kind of update to use:
    # default                            = yum upgrade
    # security                           = yum --security upgrade
    # security-severity:Critical         = yum --sec-severity=Critical upgrade
    # minimal                            = yum --bugfix update-minimal
    # minimal-security                   = yum --security update-minimal
    # minimal-security-severity:Critical =  --sec-severity=Critical update-minimal
    update_cmd = default

    # Whether a message should be emitted when updates are available,
    # were downloaded, or applied.
    update_messages = yes

    # Whether updates should be downloaded when they are available.
    download_updates = yes

    # Whether updates should be applied when they are available.  Note
    # that download_updates must also be yes for the update to be applied.
    apply_updates = no

and as you can see `apply_updates` is `no`. This should probably be set to `yes` if `security_autoupdate_enabled` is enabled.

Also `update_cmd` would be nice to have as an option ;)

/cc @FinBoWa

**Comment by geerlingguy** [comment]
@jyrkij - D'oh! That's what I get for designing the role for 6 and figuring I didn't need to change it for 7. I'll get this fixed ASAP.

**Comment by geerlingguy** [comment]
I've also confirmed that updates are enabled correctly by default in CentOS 6, so fixing in 7 now with a `lineinfile`.

**Comment by geerlingguy** [comment]
I've left out the 'update_cmd' option for now, as that would require a little more work in terms of getting it working across CentOS 6 and 7 both, not to mention what to do for Debian systems.

The way it is now (after this fix), both 6 and 7 run `yum update`, so at least they're consistent. Would be nice to have them configurable though.
