### ISSUE TITLE
Protocol settings for sshd missing

### ISSUE THREAD

**Issue by staticdev** [geerlingguy/ansible-role-security#101]
Adding [Protocol 2](https://linux.die.net/man/5/sshd_config) to sshd_config is a general security good practice.

Some references:
- https://www.tecmint.com/secure-openssh-server/
- http://www.snailbook.com/faq/ssh-1-vs-2.auto.html
- https://docstore.mik.ua/orelly/networking_2ndEd/ssh/ch03_05.htm

**Comment by geerlingguy** [comment]
The default has been `1` for some time, though — are there security scanning tools that are coming up and pointing this out, or are there systems you're using the role on that are defaulting to `1` for some reason?

**Comment by staticdev** [comment]
@geerlingguy actually after some research I saw [latest versions](https://www.openssh.com/releasenotes.html) of ssh server don't even have this parameter anymore. It is Procotol 2 only ;)
