### ISSUE TITLE
Fix Travis/Docker test idempotency for Ubuntu 14.04

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-security#11]
See: https://travis-ci.org/geerlingguy/ansible-role-security/jobs/108126454, specifically https://travis-ci.org/geerlingguy/ansible-role-security/jobs/108126454#L851

It looks like the service module is not working (at least as of 2.0.0.2) with whatever return code is coming back from fail2ban... Works for CentOS 6/7 and Ubuntu 12.04, so not sure why 14.04 is failing :/

**Comment by oxyc** [comment]
This is probably the same as with all `upstart` scripts not working. Essentially any `service foobar start/stop/status` returns the same response every time. A bit confused to why Ubuntu 12.04 passes O.o

**Comment by geerlingguy** [comment]
Dangit! Well, at least if I solve it once, I'll solve it for all :)

**Comment by oxyc** [comment]
Btw this is the source of all evil I guess https://github.com/tianon/docker-brew-ubuntu-core/blob/e406914e5f648003dfe8329b512c30c9ad0d2f9c/trusty/Dockerfile#L10:L12

**Comment by geerlingguy** [comment]
@oxyc - Do you know of another base Ubuntu image we could switch to that might overcome this?

**Comment by oxyc** [comment]
Now that I see what's actually going on Im not sure why https://github.com/tianon/dockerfiles/tree/master/sbin-init/ubuntu/upstart didn't work when I tried it. Looks like it _should_ fix it.

**Comment by geerlingguy** [comment]
Can you PR a test here (using this role) and see how it works? This role would be a bit faster for the test cycle than MySQL.

**Comment by oxyc** [comment]
For `14.04` this one seems very popular https://github.com/phusion/baseimage-docker

**Comment by geerlingguy** [comment]
Fixed in #12
