### ISSUE TITLE
Role does not support changing ssh port on Ubuntu 22

### ISSUE THREAD

**Issue by typhonius** [geerlingguy/ansible-role-security#111]
Creating a new issue to continue report from #82 as Ubuntu 22 has switched to using socket streams rather than ports. With that in place, the `Port` directive in `sshd_config` is now ignored so this Ansible module has the potential impact of locking people out of servers if port + firewall settings are changed together.

This link provides the manual steps which I've added to a custom role, although it would be good to be supported more globally -- however it's best decided to be implemented.

**Comment by bahoop** [comment]
i'm not able to extend / test the playbook in detail but I have was able to get this work by adding an `/etc/systemd/system/ssh.socket.d/override.conf` (tested on debian and ubuntu):


```
...
  vars_files:
    - vars/main.yml

  handlers:
    - name: Restart ssh socket
      ansible.builtin.shell: |
        systemctl daemon-reload
        systemctl stop ssh.socket || true
        systemctl stop ssh.service || true
        systemctl start ssh.socket

  roles:
    - role: geerlingguy.security

  post_tasks:
    - name: Create directory for ssh.socket override
      ansible.builtin.file:
        path: /etc/systemd/system/ssh.socket.d
        state: directory
        mode: '0755'

    - name: Create override.conf to change SSH port for socket activation
      ansible.builtin.copy:
        dest: /etc/systemd/system/ssh.socket.d/override.conf
        content: |
          [Socket]
          ListenStream=
          ListenStream=0.0.0.0:{{ security_ssh_port }}
        mode: '0644'
      notify: Restart ssh socket
...
```

vars/main.yml
```
...
security_ssh_port: 1042
...
```

with geerlingguy.security: 3.0.0
