### ISSUE TITLE
2.2.1 release not available in galaxy.ansible.com

### ISSUE THREAD

**Issue by githubERIK** [geerlingguy/ansible-role-security#119]
https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/security/ shows that the latest release is 2.2.0.
https://github.com/geerlingguy/ansible-role-security/tags shows that the latest release is 2.2.1.

```yaml
---
roles:
  - name: geerlingguy.security
    version: 2.2.1
```

fails with

```
geerlingguy.security was NOT installed successfully: - the specified version (2.2.1) of geerlingguy.security was not
found in the list of available versions
```

https://github.com/geerlingguy/ansible-role-security/actions/runs/6633442881/job/18021178026
shows the reason why the latest build failed: 

```bash
Run yamllint .
./tasks/fail2ban.yml
  Error: 23:4 [indentation] wrong indentation: expected 4 but found 3

Error: Process completed with exit code 1.
```

**Comment by hmgarcia7** [comment]
Is there an update on this?

**Comment by ecwyne** [comment]
I'm experiencing this as well. Was surprised when Fail2Ban wasn't restarting.

Doesn't look like any code changes are needed, just deploying to Galaxy.

Thank you so much @geerlingguy, this is an incredibly helpful role!

**Comment by geerlingguy** [comment]
@ecwyne - I've just pushed a 2.2.2 as well. No clue why the Galaxy import's not working, hopefully this one will.

**Comment by ecwyne** [comment]
@geerlingguy that worked! Thank you so much!

And thank you for your contributions to the community. II recently watched your Ansible 101 course and it was an incredible start to my Ansible journey
