### ISSUE TITLE
Logs wiped on Centos 6.4 host

### ISSUE THREAD

**Issue by paulmaunders** [geerlingguy/ansible-role-security#13]
I've tried running this role on a few different hosts, and I've just noticed that all the logs in /var/log/secure were empty on one of them. 

I think this might be due to an issue with fail2ban's log rotation on Centos 6 https://github.com/fail2ban/fail2ban/issues/44

**Comment by paulmaunders** [comment]
It looked like rsyslog had stopped on the server, restarting it seems to have brought logging back...

```
# service rsyslog status
rsyslogd dead but pid file exists
```

**Comment by geerlingguy** [comment]
Going to close this as not reproducible—but please let me know if you see the behavior happen again.
