### ISSUE TITLE
how to run this

### ISSUE THREAD

**Issue by elcangri2124** [geerlingguy/ansible-role-security#18]
Helo,

I'm new to ansible and just wanted to know to run this in a test server. I'm in the process of buying your book since it came recommended but, just wanted to know how to run this right away. Thank you!

**Comment by geerlingguy** [comment]
The easiest way would be to create an inventory for your server and a playbook that runs just this role.

Create a directory with two files:

`inventory`, with contents:

```
[myserver]
myserver.example.com
```

`playbook.yml` with contents:

```yaml
---
- hosts: myserver
  roles:
    - geerlingguy.security
```

Then run `ansible-galaxy install geerlingguy.security` to download this role to your computer (might need `sudo`), and then run `ansible-playbook playbook.yml`.

To be safe, if you're doing this on any server where a change could lock you out, make sure you run it in `--check` mode first, with `ansible-playbook --check playbook.yml`

Hope that works for you!

**Comment by elcangri2124** [comment]
thank you :) I will try this and see. I needed to test a solution at the moment while we get ansible figured out. Currently reading your book. Thank you!
