### ISSUE TITLE
Add validation to sshd_config update

### ISSUE THREAD

**Issue by rdonkin** [geerlingguy/ansible-role-security#28]
Any plans to add validation using the equivalent of `sshd -f /etc/ssh/sshd_config  -t` when updating the `sshd_config` file?  

This will prevent this role from breaking SSH, which can happen without validation - for example if someone has made an invalid change to the config without restarting `sshd`, or if a modified version of this role includes invalid config.

It could work in similar way to the `sudoers` config validation, using the `validate:` feature of `lineinfile`.

**Comment by AlexanderPavlenko** [comment]
Thanks to the absence of this validation just locked myself out of access by using `yes` instead of `'yes'` in `security_ssh_...` variable. 🤦‍♂
