### ISSUE TITLE
fail2ban sshd jail config does not rely to `security_ssh_port`

### ISSUE THREAD

**Issue by albenik** [geerlingguy/ansible-role-security#30]
Even if I specify `security_ssh_port: 123`, fail2ban jail config keep untouched and fail2ban configured for default sshd port `22`.

**Comment by geerlingguy** [comment]
Ah, yes, this is a definite bug that needs to be fixed; surprised I haven't caught this on one of my builds using a different default port, but usually those also have a more customized (in the playbook) jail config too.
