### ISSUE TITLE
Emphasize that /etc/ssh/sshd_config values must be quoted

### ISSUE THREAD

**Issue by wizonesolutions** [geerlingguy/ansible-role-security#33]
I set `security_ssh_permit_root_login` to `yes` today, and I got locked out of SSH. This is because it casted it to `True` when writing the file. That is not a valid value, and it causes SSH to fail starting.

It should cast it to `yes` instead.

I'm thinking about how to do this most elegantly and will probably send a PR.

**Comment by geerlingguy** [comment]
Yeah, this is one case where the value _must_ be quoted, since it has to be a `yes` or `no` in the resultant config file.
