### ISSUE TITLE
fail2ban sshd jail is not enabled on RHEL7/CentOS7

### ISSUE THREAD

**Issue by showaltb** [geerlingguy/ansible-role-security#39]
Not sure if this would be considered a bug or a documentation issue, but the fail2ban `sshd` jail is not enabled by default on RHEL7/CentOS7. The role just installs the `fail2ban` package but does not further configure it. On Debian, the jail is automatically enabled by the file `/etc/fail2ban/jail.d/defaults-debian.conf`, but on RHEL7/CentoOS7, all jails are disabled by default.

Possibly a solution to #30 will address this as well?

**Comment by bbaassssiiee** [comment]
fail2ban is a package that you need to configure, and test! Deploy the servver online and watch the brute-force break-in attempts logged in /var/log/secure. The idea is that fail2ban parses this log and that it adds the violating ips to an ipset that are govered by firewalld, for instance with a rich-rule:

```
firewall-cmd --zone=drop --add-rich-rule='rule source ipset=fail2ban-sshd drop'
```

The default firewalld zone should be 'drop' to comply with NIST, DISA-STIG etc.

The problem on Centos 7.6  is that the package does not work out-of-the-box. Lot's of blogs simply mention some config, but if you would actually tail /var/log/secure and inspect `ipset list fail2ban-sshd` you will see that there are regular expressions to tweak before it works.
