### ISSUE TITLE
ssh restart fails

### ISSUE THREAD

**Issue by alexparvulescu** [geerlingguy/ansible-role-security#4]
hi,

I'm setting up a new Ubuntu 14.04 machine, and the playbook fails at restarting the `ssh` service:

```
NOTIFIED: [geerlingguy.security | restart ssh] ******************************** 
failed: [myserver] => {"failed": true}
FATAL: all hosts have already failed -- aborting
PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/aparvule/miggy.retry
myserver                      : ok=7    changed=3    unreachable=0    failed=1   
```

when I run it again, it looks like it went through fine (settings are indeed updated), but still the ssh service is not restarted, I can still login on the default port.

```
PLAY RECAP ******************************************************************** 
myserver                      : ok=7    changed=0    unreachable=0    failed=0 
```

what I think is missing here is running `restart ssh ` with `sudo`.

**Comment by geerlingguy** [comment]
I'm getting the same error on Drupal VM, which I recently switched to Ubuntu 14.04. I'll take a look!

**Comment by geerlingguy** [comment]
@alexparvulescu - It looks like this is a bug in Ansible 1.9.1—please see:

  - https://github.com/ansible/ansible-modules-core/issues/1298
  - https://github.com/ansible/ansible-modules-core/pull/999 (the fix)

For now, you can downgrade to 1.8.x, wait until 1.9.2 is released, or switch to the latest version in the ansible `devel` branch.

**Comment by alexparvulescu** [comment]
I'll wait for 1.9.2 then. thanks for the update @geerlingguy!
