### ISSUE TITLE
Insecure SSH algorithms present

### ISSUE THREAD

**Issue by Alex-UK-PL** [geerlingguy/ansible-role-security#45]
The role gives a false impression that SSH is more secure by applying this role. 

In order to make sure that SSH service only allows secure (as of today) algorithms, a line with specific algorithms needs to be specified. Otherwise service will use all available cipher suites etc.
Add the following stuff wherever appropriate: 
security_ssh_ciphers: "aes128-ctr,aes192-ctr,aes256-ctr"
security_ssh_host_key_algorithms: "ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss"
security_ssh_macs: "hmac-sha2-256,hmac-sha2-512"
security_ssh_kex_algorithms: "ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256"

**Comment by Alex-UK-PL** [comment]
You may want to also add ChaCha20  if you do not want to rely on the AES only.

**Comment by bbaassssiiee** [comment]
There are alternatives to this role:
- https://github.com/dev-sec/ansible-ssh-hardening
- https://github.com/dockpack/secure_ssh
