### ISSUE TITLE
Install fail2ban: "Could not find aptitude. Using apt-get instead"

### ISSUE THREAD

**Issue by joelstein** [geerlingguy/ansible-role-security#49]
Hi Jeff! :)

I'm getting an annoying ansible warning with this role when it tries to install fail2ban:

>  [WARNING]: Could not find aptitude. Using apt-get instead

There's an easy workaround I use in my playbooks to avoid this by setting `force_apt_get: yes`.

Would you be open to adding a setting to this ansible role which lets us configure this? I'm honestly not sure what the best solution is.

**Comment by geerlingguy** [comment]
This was fixed in https://github.com/ansible/ansible/issues/56832 — should've never been a warning :)

**Comment by joelstein** [comment]
Thanks friend!
