### ISSUE TITLE
Blocks SSH

### ISSUE THREAD

**Issue by tobiassjosten** [geerlingguy/ansible-role-security#6]
Hi! I'm trying to use this role in one of my projects but I keep bumping into a problem. After provisioning it fails restarting SSH and after doing so myself I can no longer SSH into the machine.

The only configuration override I've configured is `security_ssh_permit_root_login: yes`, since I SSH as root.

Any idea what I could be doing wrong?

    TASK: [geerlingguy.security | Include OS-specific variables.] *****************
    ok: [1.2.3.4]
    
    TASK: [geerlingguy.security | Install fail2ban.] ******************************
    skipping: [1.2.3.4]
    
    TASK: [geerlingguy.security | Install fail2ban.] ******************************
    changed: [1.2.3.4]
    
    TASK: [geerlingguy.security | Ensure fail2ban is running and enabled on boot.] ***
    ok: [1.2.3.4]
    
    TASK: [geerlingguy.security | Update SSH configuration to be more secure.] ****
    changed: [1.2.3.4] => (item={'regexp': '^PasswordAuthentication', 'line': u'PasswordAuthentication False'})
    changed: [1.2.3.4] => (item={'regexp': '^PermitRootLogin', 'line': u'PermitRootLogin True'})
    ok: [1.2.3.4] => (item={'regexp': '^Port', 'line': u'Port 22'})
    
    TASK: [geerlingguy.security | Add configured user accounts to passwordless sudoers.] ***
    skipping: [1.2.3.4]
    
    TASK: [geerlingguy.security | Add configured user accounts to passworded sudoers.] ***
    skipping: [1.2.3.4]
    
    TASK: [geerlingguy.security | Install yum-cron.] ******************************
    skipping: [1.2.3.4]
    
    TASK: [geerlingguy.security | Ensure yum-cron is running and enabled on boot.] ***
    skipping: [1.2.3.4]
    
    TASK: [geerlingguy.security | Install unattended upgrades package.] ***********
    ok: [1.2.3.4]
    
    TASK: [geerlingguy.security | Copy unattended-upgrades configuration files in place.] ***
    changed: [1.2.3.4] => (item=10periodic)
    changed: [1.2.3.4] => (item=50unattended-upgrades)

    NOTIFIED: [geerlingguy.security | restart ssh] ********************************
    failed: [1.2.3.4] => {"failed": true}

    FATAL: all hosts have already failed -- aborting

**Comment by geerlingguy** [comment]
@tobiassjosten - Are you using a password to log into the remote server, or do you use key-based auth? Basically, if you would manually log in, do you enter just `ssh yourusername@example.com` and it connects right away?

**Comment by tobiassjosten** [comment]
Thanks for the rapid reply, @geerlingguy! I'm using key based authentication.

**Comment by geerlingguy** [comment]
If you leave one connection open (to the machine where things fail after applying this role), and monitor the SSH logs (auth.log or sshd.log, something like that), do you see what fails next time you try to connect?

**Comment by tobiassjosten** [comment]
Got it reproduced now – finally connected without shared SSH ControlMaster. :)

Neither auth.log, syslog nor fail2ban.log say anything and there's no sshd.log. Interestingly though:

    # netstat -tap
    Active Internet connections (servers and established)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
    tcp        0    340 myserver.com:ssh     cpc3-sgyl29-2-0-c:52777 ESTABLISHED 1427/0

    # service ssh status
    ssh start/running

**Comment by geerlingguy** [comment]
Weird... so it looks like SSH is maybe connecting at least. Maybe there's an upstream firewall that's blocking the connection? Are you on a corporate network or a proxied or VPN'ed connection?

**Comment by geerlingguy** [comment]
Also, the role had a couple bugs that have since been worked out relating to sudoers file syntax. Maybe rebuild the server again and run the role and see if it works this time?
