### ISSUE TITLE
The module does not work on bare metal machines with libvirt-bin installed.

### ISSUE THREAD

**Issue by unitynet-dk** [geerlingguy/ansible-role-security#64]
When I use the module on certain bare metal machines, the SSH setup gets completely smashed. This is about my MAAS server and my KVM host machines. Common to all of them is that they have libvit-bin installed. It seems that the module considers them as virtual machines, which they are not.

Yours sincerely
Søren Sjøstrøm
Unitynet

**Comment by geerlingguy** [comment]
I'm not quite sure how I could work around that. I haven't encountered issues on KVM hosts from a few different hosting providers I use, though I can't admit I have spent much time working with different bare metal provisioners, I do mostly cloud-based work.

**Comment by geerlingguy** [comment]
Do you have any error messages or logs or anything that could assist here? When you say the SSH setup gets smashed, is there any error message in any logs, or does Ansible say anything helpful?
