### ISSUE TITLE
SSH getting file not found errors.

### ISSUE THREAD

**Issue by gheydon** [geerlingguy/ansible-role-security#65]
I am getting the following errors. 

`failed: [x.x.x.x] (item={u'regexp': u'^PasswordAuthentication', u'line': u'PasswordAuthentication no'}) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshd -T -f /tmp/tmpbALBAx", "item": {"line": "PasswordAuthentication no", "regexp": "^PasswordAuthentication"}, "msg": "[Errno 2] No such file or directory", "rc": 2}
failed: [x.x.x.x] (item={u'regexp': u'^PasswordAuthentication', u'line': u'PasswordAuthentication no'}) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshd -T -f /tmp/tmpAGtMcq", "item": {"line": "PasswordAuthentication no", "regexp": "^PasswordAuthentication"}, "msg": "[Errno 2] No such file or directory", "rc": 2}
failed: [x.x.x.x] (item={u'regexp': u'^PermitRootLogin', u'line': u'PermitRootLogin no'}) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshd -T -f /tmp/tmp4W8JFX", "item": {"line": "PermitRootLogin no", "regexp": "^PermitRootLogin"}, "msg": "[Errno 2] No such file or directory", "rc": 2}
failed: [x.x.x.x] (item={u'regexp': u'^PermitRootLogin', u'line': u'PermitRootLogin no'}) => {"ansible_loop_var": "item", "changed": false, "cmd": "sshd -T -f /tmp/tmpNO0KfI", "item": {"line": "PermitRootLogin no", "regexp": "^PermitRootLogin"}, "msg": "[Errno 2] No such file or directory", "rc": 2}`

I am not sure why this is happening. Any ideas?

**Comment by gheydon** [comment]
I have done a little more investigation, but this is not happening always, other issues such as 

```
ok: [x.x.x.4] => (item={u'regexp': u'^PermitEmptyPasswords', u'line': u'PermitEmptyPasswords no'})
ok: [x.x.x.5] => (item={u'regexp': u'^PermitEmptyPasswords', u'line': u'PermitEmptyPasswords no'})
ok: [x.x.x.4] => (item={u'regexp': u'^ChallengeResponseAuthentication', u'line': u'ChallengeResponseAuthentication no'})
ok: [x.x.x.5] => (item={u'regexp': u'^ChallengeResponseAuthentication', u'line': u'ChallengeResponseAuthentication no'})
```

I do not see any reason why this would happen, some failing and some not.

**Comment by idolize** [comment]
I'm seeing this same behavior when I run this role on a raspberry pi (it seems to work fine on an Intel machine, however):

![image](https://github.com/geerlingguy/ansible-role-security/assets/635005/4b7d5ee0-dcce-49ea-ab57-bf84f8b6b4f6)
