### ISSUE TITLE
SSH regexp not handling all situations.

### ISSUE THREAD

**Issue by gheydon** [geerlingguy/ansible-role-security#66]
Currently the regular expressions use something like the following `^PasswordAuthentication` but it will not handle default situations

```
#PasswordAuthentication: yes
```

the expressions should really be something like `^[#]?PasswordAuthentication` so that it will handle commented out lines, and maybe add in a `\s+` to allow for a spaces to be added.

Thanks.

**Comment by gheydon** [comment]
I have finally got this working as required. Not being a Python programmer I had problems encapsulating the more complex regular expressions.

**Comment by dbrennand** [comment]
Hi 👋🏻 

Crazily enough I've just hit this exact problem on a fresh install of Raspian OS Lite. The default config has several of the lines commented out and the regular expressions are not matching 😞 .

@gheydon - Are you OK with me raising a PR to implement your changes in your fork?

**Comment by gheydon** [comment]
Yes go for it. For me it was more of a cleanliness thing so that it would alter the existing line 100% of the time instead of just appending the line to the bottom of the file and moving it out of the correct section.
