### ISSUE TITLE
[Ubuntu 20.04.1] Problems installing fail2ban

### ISSUE THREAD

**Issue by gfunosas** [geerlingguy/ansible-role-security#67]
Hello, 

We are using this security role (version 2.0.1.), in a new server with Ubuntu focal version 20.04.1, and we get this:

```
TASK [geerlingguy.security : Install fail2ban (Debian).] *******************************************************************************************************
fatal: []: FAILED! => {"changed": false, "msg": "No package matching 'fail2ban' is available"}
``` 
We've realized that the problem is that the package is not found on the 20.04.1 version of Ubuntu (`apt search fail2ban` gives 0 results, whereas in Ubuntu 20.04 it is found).

Is anyone else having this problem, or does anyone already know how to solve it? 

Thank you,

**Comment by opdavies** [comment]
I saw the same on Ubuntu 20.04, where `fail2ban` wouldn't install. I found that it was available after running `apt update` so I was able to do with with a `pre_task`:

```
pre_tasks:
  - apt:
      update_cache: true
      cache_valid_time: 3600
```
