### ISSUE TITLE
Invalid sshd_config

### ISSUE THREAD

**Issue by psaelens** [geerlingguy/ansible-role-security#7]
After running the task 'Update SSH configuration to be more secure.", the ssh_config file is invalid 

```
$ sudo sshd -T
Unsupported option False
```

vars :
```
security_ssh_password_authentication: no
security_ssh_permit_root_login: no
```

Ansible output : 
```
TASK: [geerlingguy.security | Update SSH configuration to be more secure.] ****
changed: [51.254.225.176] => (item={'regexp': '^PasswordAuthentication', 'line': u'PasswordAuthentication False'})
changed: [51.254.225.176] => (item={'regexp': '^PermitRootLogin', 'line': u'PermitRootLogin False'})
```

=> Apparently in some way the value of boolean var are misinterpreted (should be no instead of False)

**Comment by geerlingguy** [comment]
Please try using the following vars instead:

```
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
```

Using quotes makes those strings instead of YAML bools, and it should fix the issue (see the latest `defaults.yml` for more).

**Comment by psaelens** [comment]
:+1: thanks, it fixes the issue.
