### ISSUE TITLE
DOC: Additional References

### ISSUE THREAD

**Issue by westurner** [geerlingguy/ansible-role-security#70]
# Additional references

**Comment by westurner** [comment]
https://dev-sec.io/baselines/
https://github.com/dev-sec?q=ansible&type=source&language=

- https://dev-sec.io/baselines/linux/
  - https://github.com/dev-sec/ansible-os-hardening
- https://dev-sec.io/baselines/ssh/
  - https://github.com/dev-sec/ansible-ssh-hardening
  - https://github.com/dev-sec/ansible-ssh-hardening/tree/master/tests
  - https://github.com/dev-sec/ansible-ssh-hardening/blob/master/defaults/main.yml
  - https://github.com/dev-sec/ansible-ssh-hardening/blob/master/tasks/hardening.yml
- https://dev-sec.io/baselines/docker/
-

**Comment by westurner** [comment]
@geerlingguy check it

**Comment by geerlingguy** [comment]
I'm not quite sure what's being requested?

**Comment by westurner** [comment]
Compare these?
- https://github.com/geerlingguy/ansible-role-security/blob/master/tasks/ssh.yml
- https://github.com/dev-sec/ansible-ssh-hardening/blob/master/tasks/hardening.yml

**Comment by westurner** [comment]
Compare these?
- https://github.com/geerlingguy/ansible-role-security/blob/master/tasks/ssh.yml
- https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/ssh_hardening/tasks

I'm assuming there would be conflicts when installing  Ansible-role-security as well, but could be wrong

**Comment by geerlingguy** [comment]
There may be conflicts; I don't recommend trying to mix multiple security/hardening roles together. Much better to fork one and modify it to your needs, or just stick with one or the other.
