### ISSUE TITLE
SSH Allow Users and Groups

### ISSUE THREAD

**Issue by NiftyMist** [geerlingguy/ansible-role-security#79]
Should add 2 additional tasks to `tasks/ssh.yml` that configures allowed users or groups to the ssh config as an additional layer of security.

**Comment by NiftyMist** [comment]
Created a pull request to address this: https://github.com/geerlingguy/ansible-role-security/pull/80

**Comment by NiftyMist** [comment]
Bumping this just in case it is something that can be added.  :smile:

**Comment by NiftyMist** [comment]
The PR for this request has been closed by the stale bot.  I'm still using this branch in my day to day deployments so I would love for it to be merged in.  I'm going to repopen the merge request and it can be looked at as the time allows.  Keep up the good work @geerlingguy.

**Comment by geerlingguy** [comment]
@NiftyMist - I like the addition, but can't seem to reopen that PR. Happy to merge one if you can re-create the PR (see https://github.com/geerlingguy/ansible-role-security/pull/80#issuecomment-1002304598).

**Comment by geerlingguy** [comment]
Oh, just found 84...
