### ISSUE TITLE
 syntax error near line 28: deploy ALL=(ALL)

### ISSUE THREAD

**Issue by chriswayg** [geerlingguy/ansible-role-security#8]
Hi, and thanks for sharing this very useful unusable role!

I'm getting the folling errror:
```
## vars:
security_sudoers_passworded: 
  - deploy

## running Ansible:
TASK: [geerlingguy.security | Add configured user accounts to passworded sudoers.] ***
failed: [89.163.212.62] => (item=deploy) => {"failed": true, "item": "deploy"}
msg: failed to validate: rc:1 error:>>> /tmp/tmps8viv2: syntax error near line 28 <<<

## Debian Jessie on the server:
$ cat /tmp/tmps8viv2
##...line 28: ...
deploy ALL=(ALL)

$ visudo -cf /tmp/tmps8viv2
>>> /tmp/tmps8viv2: syntax error near line 28 <<<
parse error in /tmp/tmps8viv2 near line 28
```

It works when changing the line to `deploy ALL=(ALL) ALL`, which is the syntax I'm familiar with. 

Visudo doesn't seem to like your syntax in ssh.yml line 31

Chris

**Comment by chriswayg** [comment]
Hi, nice that its fixed! I should have proof-read my bug report before posting.

Scratch this word: '~~unusable~~'. I simply meant to say "thanks for sharing this **very useful** role!" - no criticism implied.

**Comment by geerlingguy** [comment]
Haha, no problem!
