### ISSUE TITLE
sudoes file given more permission than needed

### ISSUE THREAD

**Issue by staticdev** [geerlingguy/ansible-role-security#99]
sudoes file needs 0400 and it is being edited with 0644. Let's apply the least privileged principle from `Ansible for Devops` of @geerlingguy ;)

**Comment by geerlingguy** [comment]
It looks like it's actually 440 by default on a fresh install of Debian at least:

```
-r--r-----   1 root root    669 Feb 27  2021 sudoers
```

**Comment by staticdev** [comment]
@geerlingguy I update the PR and switched to Debian's default then.
